version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - ls -la #to verify files
      - ls -la build/ #to verify build folder

  post_build:
    commands:
      - aws s3 ls s3://guide.gonzalo-munoz.com
      - aws s3 sync build/ s3://guide.gonzalo-munoz.com --delete

artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'