version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo "Build completed"
      - ls -la build # Para verificar los archivos
  post_build:
    commands:
      - aws s3 sync build/ s3://guide.gonzalo-munoz.com --delete
      - aws cloudfront create-invalidation --distribution-id E1HJ7VJHGITQNV --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build